# Generated by Django 5.2.17 on 2026-09-25 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('weight', models.FloatField(default=1)),
                ('relief', models.BooleanField(default=False)),
                ('meals', models.IntegerField(default=0)),
                ('need', models.IntegerField(default=0)),
                ('vols', models.IntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=300)),
                ('city_code', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SimState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surge', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=True)),
                ('meals_total', models.IntegerField(default=0)),
                ('kg_total', models.FloatField(default=0)),
                ('pickup_median', models.IntegerField(default=23)),
                ('streams', models.JSONField(default=dict)),
                ('grades', models.JSONField(default=dict)),
                ('seq', models.IntegerField(default=2400)),
                ('report_seq', models.IntegerField(default=310)),
                ('last_tick', models.DateTimeField(blank=True, null=True)),
                ('last_spawn', models.DateTimeField(blank=True, null=True)),
                ('last_periodic', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulkGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=40)),
                ('kg_per_day', models.IntegerField()),
                ('diverted', models.IntegerField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('due', 'Due in 3 days'), ('missing', 'Missing'), ('sent', 'Notice sent')], default='valid', max_length=10)),
                ('reg', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_generators', to='core.city')),
            ],
            options={
                'ordering': ['city', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('people', 'Shelter or kitchen'), ('relief', 'Relief camp'), ('animal', 'Animal shelter'), ('compost', 'Compost unit')], max_length=10)),
                ('dist_km', models.FloatField()),
                ('urgency', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('veg_only', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('slot', models.CharField(blank=True, max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='core.city')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('donor', models.CharField(max_length=120)),
                ('food', models.CharField(max_length=120)),
                ('cat', models.CharField(default='veg', max_length=10)),
                ('veg', models.BooleanField(default=True)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('kg', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('hours', models.FloatField()),
                ('temp_c', models.IntegerField()),
                ('packaging', models.CharField(max_length=10)),
                ('checks', models.IntegerField()),
                ('score', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
                ('factors', models.JSONField(default=dict)),
                ('streams', models.JSONField(default=dict)),
                ('shelf_ms', models.BigIntegerField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('listed', 'Waiting for a match'), ('matched', 'Volunteer on the way'), ('picked', 'In transit'), ('delivered', 'Delivered'), ('composted', 'Sent to compost')], db_index=True, default='listed', max_length=10)),
                ('volunteer', models.CharField(blank=True, max_length=80)),
                ('pick_at', models.DateTimeField(blank=True, null=True)),
                ('drop_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('no_resp', models.BooleanField(default=False)),
                ('log', models.JSONField(default=list)),
                ('dist_for', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('volunteer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.city')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.receiver')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=60)),
                ('where', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('new', 'Sent to ward team'), ('assigned', 'Team on the way'), ('cleared', 'Cleared')], default='new', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('t2', models.DateTimeField(blank=True, null=True)),
                ('has_photo', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('deliveries', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('online', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.city')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-credits'],
            },
        ),
    ]
